server:
  port: 8765
spring:
  application:
    name: gateway
  cloud:
    gateway:
      default-filters:
        - TokenRelay=
      routes:
        - id: resourceRoute
          uri: http://localhost:8080/
          predicates:
            - Path=/v1/api/resources/**

        - id: angular
          uri: http://localhost:4200/
          predicates:
            - Path=/**

  security:
    oauth2:
      client:
        registration:
          gateway:
            provider: spring
            client-id: gateway
            client-secret: secret
            scope: openid, profile
            authorization-grant-type: authorization_code
            redirect-uri: http://127.0.0.1:8765/login/oauth2/code/gateway
        provider:
          spring:
            issuer-uri: http://localhost:9000