spring:
  application:
    name: authorization-server
  datasource:
    url: "jdbc:mysql://localhost:3306/auth-users?autoReconnect=true&useSSL=false&createDatabaseIfNotExist=true"
    username: root
    password: root
    hikari:
      pool-name: authorizationServerPool
      connection-timeout: 50000
      idle-timeout: 300000
      max-lifetime: 900000
      maximum-pool-size: 10
      minimum-idle: 3
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        useLocalSessionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: false
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
server:
  port: 9000

###########################################################################################
#                                 Logging configurations                                  #
###########################################################################################
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %green([%thread]) %highlight(%level)  %logger - %msg%n"
    file: "%d{dd-MM-yyyy HH:mm:ss.SSS} [%thread] %-5level %logger.%M - %msg%n"
    dateformat: yyyy-MM-dd HH:mm:ss
  file:
    name: logs/authorization-server.log
  logback:
    rollingpolicy:
      file-name-pattern: logs/archived/authorization-server.%d{yyyy-MM-dd}.%i.log
      max-history: 5
      max-file-size: 1250MB
  level:
    root: WARN
    io.warehouse13: INFO
    org.springframework: INFO
    org.springframework.security: TRACE
    org.springframework.security.oauth2: TRACE
    org.hibernate: INFO
